// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReadableDeviceMemory } from "./ReadableDeviceMemory";

export interface Device { osType: string, memory: ReadableDeviceMemory, }