// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Dir = "Home" | "Pictures" | "Videos" | "Documents" | "Downloads" | "Audio" | "Desktop" | "FileSync" | { "Other": string };