#!/bin/bash 


# name:         install-toolchain 
# description:    This script is used to install the necessary packages for the application to run locally 
# parameters:    none
# last modified : May 10, 2024



# the toolchains  required for the application to run
toolchain=(node npm make yarn rustc cargo)


# check if the toolchain is installed
for tool in ${toolchain[@]}; do
    if ! command -v $tool &> /dev/null; then
        echo "$tool is not installed"
        exit 1
    fi
done



# if the tool chain is not installed , detect the operating system and install the toolchain
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Linux
    sudo apt-get update
    sudo apt-get install nodejs
    sudo apt-get install npm
    sudo apt-get install make
    sudo apt-get install yarn
    install_rust
elif [[ "$OSTYPE" == "darwin"* ]]; then
    # Mac OSX
    brew install node
    brew install npm
    brew install make
    brew install yarn
    brew install rustc
    brew install cargo
else
    echo "Unsupported OS"
    exit 1
fi




# install rust for unix systems
install_rust() {
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    source $HOME/.cargo/env
    rustup update
    rustup default stable
    rustup component add rustfmt
    rustup component add clippy
}