// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MyDisk } from "./MyDisk";

export interface Drives { arrayOfDrives: Array<MyDisk>, }