// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Drives } from "./Drives";

export interface SystemInformation {
  systemName: string;
  disk: Drives;
  availableDisk: string;
  usedDisk: string;
  port: bigint;
  remainingTime: string | null;
  ipAddress: string;
  serverBaseUrl: string;
}
