// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TransferHistory { id: string, fileName: string, fileSize: string, date: string, transactionType: string, recipient: string, }